# This file was generated by GoReleaser. DO NOT EDIT.
class Fngprint < Formula
  desc "Application to create and store directory fingerprint from all its files in a tree"
  homepage "https://github.com/nejckorasa/dir-fingerprint/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nejckorasa/dir-fingerprint/releases/download/v0.2.0/dir-fingerprint_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "448e49647b2f889ab12f345df418d808723207d3d6d5bd7f4d06ea89020303f3"
  elsif OS.linux?
    url "https://github.com/nejckorasa/dir-fingerprint/releases/download/v0.2.0/dir-fingerprint_0.2.0_Linux_x86_64.tar.gz"
    sha256 "71e8e192cd122a07f18111288d71a172269ce275ab8417d2842c644845866b5b"
  end

  def install
    bin.install "fngprint"
  end
end
