# This file was generated by GoReleaser. DO NOT EDIT.
class Fngprint < Formula
  desc "Application to create and store directory fingerprint from all its files in a tree"
  homepage "https://github.com/nejckorasa/dir-fingerprint/"
  version "0.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nejckorasa/dir-fingerprint/releases/download/v0.2.3/dir-fingerprint_0.2.3_Darwin_x86_64.tar.gz"
    sha256 "d9456e8e063779831ce3bae5d622430a47d879cbd25955f6489cca5fdb4d3902"
  elsif OS.linux?
    url "https://github.com/nejckorasa/dir-fingerprint/releases/download/v0.2.3/dir-fingerprint_0.2.3_Linux_x86_64.tar.gz"
    sha256 "4d91549bcc6d48ef574e0cf6e1e891249f2fdf26672db1a5e910fb5212fd7cee"
  end

  def install
    bin.install "dir-fingerprint"
  end
end
